# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# api_key: 'key-38097e04ba2b86dbfa2eca20f81e5b55'
# domain: 'sandboxd4cb237c3f244c2f88e631e0e7772782.mailgun.org'
# username: 'postmaster@sandboxd4cb237c3f244c2f88e631e0e7772782.mailgun.org'
# password: 'b33c71d7b46fd82f51bf01be9436a02a'

# GMAIL_SMTP_USER: ''
# GMAIL_SMTP_PASSWORD: ''

development:
  secret_key_base: b96886a46e427c6b0d23c89224178805667dc6bd29b4dd48088b9de6cdc2f33d992943b6e6bf913474bc64c54253ad8a6109abdc8e2789a6f94c0c497b374207
  SENDGRID_API_KEY: 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

test:
  secret_key_base: 54f5097635fab568bbddcfb151455a97dade7f8e27d40f7e80921011f71e4387210331f5d3c65584a28d9b0d172e0f08142119daf4fa9bf77816f9060ec14d18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  SENDGRID_API_KEY: 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

